name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  damaUI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Publish to Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            FB_API_KEY=${{ secrets.FB_API_KEY }}
            FB_DATABASE_URL==${{ secrets.FB_DATABASE_URL }}
            FB_AUTH_DOMAIN=${{ secrets.FB_AUTH_DOMAIN }}
            FB_PROJECT_ID=${{ secrets.FB_PROJECT_ID }}
            FB_STORAGE_BUCKET=${{ secrets.FB_STORAGE_BUCKET }}
            FB_MESSAGING_SENDER_ID=${{ secrets.FB_MESSAGING_SENDER_ID }}
            FB_APP_ID=${{ secrets.FB_APP_ID }}
            FB_MEASUREMENT_ID=${{ secrets.FB_MEASUREMENT_ID }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dama-ui:latest
